In [ ]:
import re
from collections import Counter
from pathlib import Path

import pandas as pd

data_dir = Path("../data/raw")

AllClinicalXX – combines all the data from AccelerometryXX,
BiomarkersXX, JointSxXX, MedHistXX, NutritionXX, PhysExamXX, and
SubjectCharXX.

In [2]:
df = pd.read_csv(data_dir / "AllClinical00.csv")

In [3]:
print(df.shape)

n_rows, n_cols = df.shape

(4796, 1187)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4796 entries, 0 to 4795
Columns: 1187 entries, ID to V00WORKAMT
dtypes: float64(251), int64(3), str(933)
memory usage: 43.4 MB

In [5]:
prefixes = [col[:3] for col in df.columns]

Counter(prefixes).most_common()

[('V00', 905), ('P01', 233), ('P02', 47), ('ID', 1), ('VER', 1)]

V00 Baseline: Enrollment

P01 Baseline: Screening

P02 Baseline: Initial Eligibility

In [6]:
for prefix in ['V00', 'P01', 'P02']:
    cols = [c for c in df.columns if c.startswith(prefix)]

    print(f"\n{prefix}: {len(cols)} variables")
    print(cols)

V00: 905 variables
['V00BLDCOLL', 'V00BLDHRS1', 'V00BLDHRS2', 'V00BLDRAW1', 'V00BLDRAW2', 'V00BLSURD1', 'V00BLSURD2', 'V00CITRATE', 'V00EDTA', 'V00excess1', 'V00excess2', 'V00hemat1', 'V00hemat2', 'V00hoursp1', 'V00hoursp2', 'V00hrsuc1', 'V00hrsuc2', 'V00illpwk1', 'V00illpwk2', 'V00LEAKAG1', 'V00LEAKAG2', 'V00MRSEQNL', 'V00MRSEQNR', 'V00MULTST1', 'V00MULTST2', 'V00othvp1', 'V00othvp2', 'V00pdate1', 'V00pdate2', 'V00PLAQHR1', 'V00PLAQHR2', 'V00qovp1', 'V00qovp2', 'V00SEAQHR1', 'V00SEAQHR2', 'V00SERUM', 'V00ucdate1', 'V00ucdate2', 'V00URINHR1', 'V00URINHR2', 'V00URINOB1', 'V00URINOB2', 'V00URNCOLL', 'V00URSURD1', 'V00URSURD2', 'V00vcoll1', 'V00vcoll2', 'V00vein1', 'V00vein2', 'V00void1', 'V00void2', 'V00SF1', 'V00SF2', 'V00SF3', 'V00SF4', 'V00SF5', 'V00SF6', 'V00SF7', 'V00SF8', 'V00SF9', 'V00SF10', 'V00SF11', 'V00SF12', 'V00WPRKN1', 'V00WPRKN2', 'V00WPRKN3', 'V00WPRKN4', 'V00WPRKN5', 'V00KPRKN1', 'V00KPRKN2', 'V00KPRKN3', 'V00P7RKFR', 'V00WSRKN1', 'V00WSRKN2', 'V00KSXRKN1', 'V00KSXRKN2', 'V00KSXRKN3', 'V00KSXRKN4', 'V00KSXRKN5', 'V00DIRKN1', 'V00DIRKN2', 'V00DIRKN3', 'V00DIRKN4', 'V00DIRKN5', 'V00DIRKN6', 'V00DIRKN7', 'V00DIRKN8', 'V00DIRKN9', 'V00DIRKN10', 'V00DIRKN11', 'V00DIRKN12', 'V00DIRKN13', 'V00DIRKN14', 'V00DIRKN15', 'V00DIRKN16', 'V00DIRKN17', 'V00WPLKN1', 'V00WPLKN2', 'V00WPLKN3', 'V00WPLKN4', 'V00WPLKN5', 'V00KPLKN1', 'V00KPLKN2', 'V00KPLKN3', 'V00P7LKFR', 'V00WSLKN1', 'V00WSLKN2', 'V00KSXLKN1', 'V00KSXLKN2', 'V00KSXLKN3', 'V00KSXLKN4', 'V00KSXLKN5', 'V00DILKN1', 'V00DILKN2', 'V00DILKN3', 'V00DILKN4', 'V00DILKN5', 'V00DILKN6', 'V00DILKN7', 'V00DILKN8', 'V00DILKN9', 'V00DILKN10', 'V00DILKN11', 'V00DILKN12', 'V00DILKN13', 'V00DILKN14', 'V00DILKN15', 'V00DILKN16', 'V00DILKN17', 'V00KOOSFX1', 'V00KOOSFX2', 'V00KOOSFX3', 'V00KOOSFX4', 'V00KOOSFX5', 'V00KQOL1', 'V00KQOL2', 'V00KQOL3', 'V00KQOL4', 'V00KGLRS', 'V00HSPSS', 'V00HSMSS', 'V00WOMKPR', 'V00KOOSKPR', 'V00WOMSTFR', 'V00KOOSYMR', 'V00WOMADLR', 'V00WOMKPL', 'V00KOOSKPL', 'V00WOMSTFL', 'V00KOOSYML', 'V00WOMADLL', 'V00KOOSFSR', 'V00KOOSQOL', 'V00P7RKRCV', 'V00P7LKRCV', 'V00WOMTSL', 'V00WOMTSR', 'V00HRTAT', 'V00HRTFAIL', 'V00BYPLEG', 'V00STROKE', 'V00ASTHMA', 'V00ASTMEDS', 'V00AMWHEN', 'V00LUNG', 'V00LGMEDS', 'V00LMWHEN', 'V00ULCER', 'V00ULCERDX', 'V00DIAB', 'V00DIABTX1', 'V00DIABTX2', 'V00DIABTX3', 'V00DIABTX4', 'V00DIABPR1', 'V00DIABPR2', 'V00DIABPR3', 'V00KIDFXN', 'V00KIDTRAN', 'V00RA', 'V00RAMEDS', 'V00POLYRH', 'V00LIVDAM', 'V00CANCER', 'V00BONEFX', 'V00HIPFX', 'V00HIPFXAG', 'V00SPNFX', 'V00SPNFXAG', 'V00FALL', 'V00WMXAGE1', 'V00WMXAGE2', 'V00WMXAGE3', 'V00WMXAGE4', 'V00WMXAGE5', 'V00WMXAGE6', 'V00WMXAGE7', 'V00WMNAGE1', 'V00WMNAGE2', 'V00WMNAGE3', 'V00WMNAGE4', 'V00WMNAGE5', 'V00WMNAGE6', 'V00WMNAGE7', 'V00SMOKE', 'V00SMKAGE', 'V00SMKNEV', 'V00SMKAVE', 'V00SMKNOW', 'V00SMKAMT', 'V00SMKSTOP', 'V00PIPE', 'V00PIPEAGE', 'V00PIPENEV', 'V00PIPENOW', 'V00PIPEAMT', 'V00PIPSTOP', 'V00DRNKAMT', 'V00DRKMORE', 'V00CESD1', 'V00CESD2', 'V00CESD3', 'V00CESD4', 'V00CESD5', 'V00CESD6', 'V00CESD7', 'V00CESD8', 'V00CESD9', 'V00CESD10', 'V00CESD11', 'V00CESD12', 'V00CESD13', 'V00CESD14', 'V00CESD15', 'V00CESD16', 'V00CESD17', 'V00CESD18', 'V00CESD19', 'V00CESD20', 'V00TYLEN', 'V00NSAIDS', 'V00NSAIDRX', 'V00COXIBS', 'V00NARCOT', 'V00SAME', 'V00MSM', 'V00DOXYCYC', 'V00PNMEDT', 'V00CHON', 'V00GLUC', 'V00KNINJ', 'V00HYALKN', 'V00STERKN', 'V00TEST', 'V00TESTUSE', 'V00ESTR', 'V00ESTRUSE', 'V00GNRH', 'V00GNRHUSE', 'V00PTH', 'V00PTHUSE', 'V00BISPHOS', 'V00BISPYRS', 'V00BISPUSE', 'V00CAM12', 'V00ACUTNUM', 'V00ACUTCUR', 'V00ACUSNUM', 'V00ACUSCUR', 'V00CHELCUR', 'V00CHELNUM', 'V00CHIRNUM', 'V00CHIRCUR', 'V00FOLKNUM', 'V00FOLKCUR', 'V00HOMENUM', 'V00HOMECUR', 'V00MASSNUM', 'V00MASSCUR', 'V00DIET12', 'V00VITM12', 'V00HERB12', 'V00RUBS12', 'V00BRAC12', 'V00YOGA12', 'V00RELA12', 'V00SPIR12', 'V00RX30', 'V00RX30NUM', 'V00COMORB', 'V00FALLCV', 'V00HT25MM', 'V00WT25KG', 'V00WTMAXKG', 'V00WTMINKG', 'V00SMOKER', 'V00SMKPKYR', 'V00PSMOKER', 'V00PSMKYR', 'V00CESD', 'V00HYAINJR', 'V00HYAINJL', 'V00STRINJR', 'V00STRINJL', 'V00BISPTYP', 'V00CHNFQCV', 'V00GLCFQCV', 'V00HYINJCV', 'V00STINJCV', 'V00ACUTCV', 'V00ACUSCV', 'V00CHELCV', 'V00CHIRCV', 'V00FOLKCV', 'V00HOMECV', 'V00MASSCV', 'V00DIETCV', 'V00VITMCV', 'V00RUBCV', 'V00CAPSNCV', 'V00BRACCV', 'V00YOGACV', 'V00HERBCV', 'V00RELACV', 'V00SPIRCV', 'V00RXANALG', 'V00RXVLCXB', 'V00RXFLUOR', 'V00RXCLCTN', 'V00RXBISPH', 'V00RXIHYAL', 'V00RXRFCXB', 'V00RXNARC', 'V00RXISTRD', 'V00RXCOX2', 'V00RXCHOND', 'V00RXOTHAN', 'V00RXGLCSM', 'V00RXACTM', 'V00RXMSM', 'V00RXNSAID', 'V00RXASPRN', 'V00RXNTRAT', 'V00RXRALOX', 'V00RXVIT_D', 'V00RXOSTRD', 'V00RXCLCXB', 'V00RXTPRTD', 'V00RXSALIC', 'V00RXSAME', 'V00OTHCAMC', 'V00OTHCAM', 'V00FFQ1', 'V00FFQSZ1', 'V00FFQ2', 'V00FFQSZ2', 'V00FFQ3', 'V00FFQSZ3', 'V00FFQ4', 'V00FFQSZ4', 'V00FFQ5', 'V00FFQ6', 'V00FFQSZ6', 'V00FFQ7', 'V00FFQSZ7', 'V00FFQ8', 'V00FFQSZ8', 'V00FFQ9', 'V00FFQSZ9', 'V00FFQ10', 'V00FFQSZ10', 'V00FFQ11', 'V00FFQSZ11', 'V00FFQ12', 'V00FFQSZ12', 'V00FFQ13', 'V00FFQSZ13', 'V00FFQ14', 'V00FFQSZ14', 'V00FFQ15', 'V00FFQSZ15', 'V00FFQ16', 'V00FFQSZ16', 'V00FFQ17', 'V00FFQSZ17', 'V00FFQ18', 'V00FFQSZ18', 'V00FFQ19', 'V00FFQSZ19', 'V00FFQ20', 'V00FFQSZ20', 'V00FFQ21', 'V00FFQSZ21', 'V00FFQ22', 'V00FFQSZ22', 'V00FFQ23', 'V00FFQSZ23', 'V00FFQ24', 'V00FFQSZ24', 'V00FFQ25', 'V00FFQSZ25', 'V00FFQ26', 'V00FFQSZ26', 'V00FFQ27', 'V00FFQSZ27', 'V00FFQ28', 'V00FFQSZ28', 'V00FFQ29', 'V00FFQSZ29', 'V00FFQ30', 'V00FFQ31', 'V00FFQSZ31', 'V00FFQ32', 'V00FFQSZ32', 'V00FFQ33', 'V00FFQSZ33', 'V00FFQ34', 'V00FFQSZ34', 'V00FFQ35', 'V00FFQ36', 'V00FFQSZ36', 'V00FFQ37', 'V00FFQSZ37', 'V00FFQ38', 'V00FFQSZ38', 'V00FFQ39', 'V00FFQ40', 'V00FFQSZ40', 'V00FFQ41', 'V00FFQSZ41', 'V00FFQ42', 'V00FFQSZ42', 'V00FFQ43', 'V00FFQSZ43', 'V00FFQ44', 'V00FFQ45', 'V00FFQSZ45', 'V00FFQ46', 'V00FFQSZ46', 'V00FFQ47', 'V00FFQSZ47', 'V00FFQ48', 'V00FFQSZ48', 'V00FFQ49', 'V00FFQSZ49', 'V00FFQ50', 'V00FFQSZ50', 'V00FFQ51', 'V00FFQSZ51', 'V00FFQ52', 'V00FFQSZ52', 'V00FFQ53', 'V00FFQSZ53', 'V00FFQ54', 'V00FFQSZ54', 'V00FFQ55', 'V00FFQSZ55', 'V00FFQ56', 'V00FFQSZ56', 'V00FFQ57', 'V00FFQSZ57', 'V00FFQ58', 'V00FFQSZ58', 'V00FFQ59', 'V00FFQSZ59', 'V00FFQ60', 'V00FFQ61', 'V00FFQSZ61', 'V00FFQ62', 'V00FFQSZ62', 'V00FFQ63', 'V00FFQSZ63', 'V00FFQ64', 'V00FFQSZ64', 'V00FFQ65', 'V00FFQSZ65', 'V00FFQ66', 'V00FFQSZ66', 'V00FFQ67', 'V00FFQ68', 'V00FFQSZ68', 'V00FFQ69', 'V00FFQSZ69', 'V00FFQ70', 'V00FFQSZ70', 'V00FFQ71', 'V00FFQ72', 'V00FFQ73', 'V00FFQYR74', 'V00FFQYR75', 'V00FFQYR76', 'V00FFQYR77', 'V00FFQYR78', 'V00FFQYR79', 'V00FFQYR80', 'V00FFQYR81', 'V00FFQYR82', 'V00FFQYR83', 'V00FFQYR84', 'V00FFQYR85', 'V00FFQYR86', 'V00FFQ87', 'V00FFQ88', 'V00FFQ89', 'V00VIT1', 'V00VIT2', 'V00VIT3', 'V00VIT4', 'V00VIT5', 'V00VIT6', 'V00VIT7', 'V00VIT8', 'V00VIT9', 'V00VIT10', 'V00VIT11', 'V00VIT12', 'V00VIT13', 'V00FFQ90', 'V00FFQ91', 'V00FFQ92', 'V00FFQ93', 'V00FFQ94', 'V00FFQ95', 'V00FFQ96', 'V00FFQ97', 'V00FFQ98', 'V00FFQ99', 'V00FFQ100', 'V00FFQ101', 'V00FFQ102', 'V00MVIT1CV', 'V00STRTBCV', 'V00ANTOXCV', 'V00VITACV', 'V00BCARCV', 'V00VITECV', 'V00FOLATCV', 'V00CALCMCV', 'V00ZINCCV', 'V00IRONCV', 'V00SLNMCV', 'V00VITDCV', 'V00VITCCV', 'V00DTDFIB', 'V00SUPVITD', 'V00FIBVGFR', 'V00SUPB12', 'V00DTCAFFN', 'V00SRVFAT', 'V00DTAIU', 'V00DTCHOL', 'V00PCTCOL1', 'V00DTPHOS', 'V00DTVITC', 'V00DTB1', 'V00PCTXLS', 'V00SUPB2', 'V00PCTCOL9', 'V00DTVITK', 'V00DTRET', 'V00SUPVITE', 'V00SUPNIAC', 'V00DTANZN', 'V00DTLUT', 'V00BAPFAT', 'V00PCTCARB', 'V00PCTSWT', 'V00DTACAR', 'V00SUPCA', 'V00SRVGRN', 'V00SRVFRT', 'V00SUPFOL', 'V00DTBCAR', 'V00DTPROT', 'V00NWARNS', 'V00DTPOTA', 'V00DTSFAT', 'V00SUPVITC', 'V00DTOLEC', 'V00SUPBCAR', 'V00DTKCAL', 'V00BAPPROT', 'V00BAPCARB', 'V00SUPVITA', 'V00SUPB6', 'V00NFDSDAY', 'V00DTNIAC', 'V00FIBBEAN', 'V00DTNA', 'V00DTARE', 'V00DTLYC', 'V00DTFAT', 'V00PCTSMAL', 'V00SUPFE', 'V00SUPCU', 'V00DTB12', 'V00DTGEN', 'V00DTMETH', 'V00SUPZINC', 'V00SRVVEG', 'V00DTCALC', 'V00SUPMG', 'V00DTDAID', 'V00SRVMEAT', 'V00DTFE', 'V00FIBGRN', 'V00DTCYST', 'V00DTSF', 'V00PCTPROT', 'V00SRVDRY', 'V00DTB6', 'V00SUPB1', 'V00SUPSE', 'V00DTMG', 'V00PCTFAT', 'V00DTVITD', 'V00DTPROA', 'V00DTCARB', 'V00PCTALCH', 'V00DTFOL', 'V00DTLIN', 'V00PCTLARG', 'V00DTVITE', 'V00NNOSERV', 'V00NSKIP', 'V00DTCRYP', 'V00PCTMEDS', 'V00DTRIBO', 'V00NERRORS', 'V00DTZINC', 'V00FFQFLG5', 'V00FFQFLG2', 'V00FFQFLG1', 'V00FFQFLG4', 'V00FFQFLG3', 'V00FFQSZW', 'V00FFQSZL', 'V00BPSTFID', 'V00BPCFSZ', 'V00BPARM', 'V00BPTERM', 'V00BPSYS', 'V00BPDIAS', 'V00RPSTFID', 'V00RPAVG', 'V00ACSTFID', 'V00MAXCIRC', 'V00SCSTFID', 'V00CSTSGL', 'V00RCSTFID', 'V00CSTREP1', 'V00CSTIME1', 'V00CSTNUM1', 'V00CSTREP2', 'V00CSTIME2', 'V00CSTNUM2', 'V00KIKBALL', 'V00EKRSR', 'V00RLLGTH', 'V00RLBACK', 'V00RLARM', 'V00RLHORIZ', 'V00RLVERT', 'V00REXPN', 'V00REXCOMP', 'V00REXWHY1', 'V00REXWHY2', 'V00REXWHY3', 'V00REXWHY4', 'V00REXWHY5', 'V00RFXPN', 'V00RFXCOMP', 'V00RFXWHY1', 'V00RFXWHY2', 'V00RFXWHY3', 'V00RFXWHY4', 'V00RFXWHY5', 'V00EKRSL', 'V00LLLGTH', 'V00TRANSET', 'V00LLBACK', 'V00LLARM', 'V00LLHORIZ', 'V00LLVERT', 'V00LEXPN', 'V00LEXCOMP', 'V00LEXWHY1', 'V00LEXWHY2', 'V00LEXWHY3', 'V00LEXWHY4', 'V00LEXWHY5', 'V00LFXPN', 'V00LFXCOMP', 'V00LFXWHY1', 'V00LFXWHY2', 'V00LFXWHY3', 'V00LFXWHY4', 'V00LFXWHY5', 'V00W2STFID', 'V00STEPST1', 'V00TIMET1', 'V00WLK20T1', 'V00STEPST2', 'V00TIMET2', 'V00WLK20T2', 'V00WLKAID', 'V00W4STFID', 'V00W20COMP', 'V00WALKER', 'V00SAFEWLK', 'V00HRB4WLK', 'V00RESTT1', 'V00RESTT2', 'V00RESTT3', 'V00RESTT4', 'V00RESTT5', 'V00RESTT6', 'V00RESTT7', 'V00RESTT8', 'V00RESTT9', 'V00RESTT10', 'V00NUMSTOP', 'V00HR400WK', 'V00HR135', 'V00CANEUSE', 'V00COMP10', 'V00REASW1', 'V00REASW2', 'V00REASW3', 'V00REASW4', 'V00REASW5', 'V00REASW6', 'V00REASW7', 'V00REASW8', 'V00REASW9', 'V00REASW10', 'V00REASW11', 'V00REASW12', 'V00REASW13', 'V00REASW14', 'V00REASW15', 'V00REASW16', 'V00DISCOMF', 'V00SOB400W', 'V00WHE400W', 'V00PN400W', 'V00OTH400W', 'V00RPN400W', 'V00RPWKTYP', 'V00RPWKPRV', 'V00LPN400W', 'V00LPWKTYP', 'V00LPWKPRV', 'V00NPN400W', 'V00DKP400W', 'V00RFP400W', 'V00K1STFID', 'V00RKPATPN', 'V00LKPATPN', 'V00RKEFFB', 'V00RKEFFPT', 'V00LKEFFB', 'V00LKEFFPT', 'V00RKRFXPN', 'V00LKRFXPN', 'V00RKLTTPN', 'V00RKMTTPN', 'V00RKABPN', 'V00LKLTTPN', 'V00LKMTTPN', 'V00LKABPN', 'V00RKPFCRE', 'V00LKPFCRE', 'V00RKPGDPN', 'V00LKPGDPN', 'V00LLWGT', 'V00RLWGT', 'V00ABCIRC', 'V00CS5', 'V00CSPACE', 'V00REXP1CV', 'V00REXP2CV', 'V00RFXP1CV', 'V00RFXP2CV', 'V00LEXP1CV', 'V00LEXP2CV', 'V00LFXP1CV', 'V00LFXP2CV', 'V0020MPACE', 'V00400MTR', 'V00KEXAMK', 'V00RKFHDEG', 'V00LKFHDEG', 'V00RKALNMT', 'V00LKALNMT', 'V00isstfid', 'V00isexmdt', 'V00rftrial', 'V00rfmaxf', 'V00rfTLPL', 'V00rfTHPL', 'V00rfTLRL', 'V00rfTHRL', 'V00retrial', 'V00remaxf', 'V00reTLPL', 'V00reTHPL', 'V00reTLRL', 'V00reTHRL', 'V00lftrial', 'V00lfmaxf', 'V00lfTLPL', 'V00lfTHPL', 'V00lfTLRL', 'V00lfTHRL', 'V00letrial', 'V00lemaxf', 'V00leTLPL', 'V00leTHPL', 'V00leTLRL', 'V00leTHRL', 'V00CALLDOC', 'V00HRELG', 'V00SYSELG', 'V00DIASELG', 'V00400MCMP', 'V00400MTIM', 'V00rexcmp2', 'V00lexcmp2', 'V00rfxcmp2', 'V00lfxcmp2', 'V00400PAIN', 'V00lkdefcv', 'V00rkdefcv', 'V00400EXCL', 'V00HOSPSUR', 'V00rfSFR', 'V00leSFR', 'V00lfSFP', 'V00reSFP', 'V00reSFR', 'V00lfSFR', 'V00rfSFP', 'V00leSFP', 'V00AGE', 'V00CEMPLOY', 'V00CUREMP', 'V00EDCV', 'V00ENRCR1', 'V00ENRCR2', 'V00ENRCR3', 'V00ENRCR4', 'V00ENRCR5', 'V00ENRCR6', 'V00ENREXCP', 'V00EVDATE', 'V00HANDED', 'V00HLTHCAR', 'V00HLTHCOV', 'V00HOUACT1', 'V00HOUACT2', 'V00HOUACT3', 'V00HOUACT4', 'V00HOUACT5', 'V00HOUACT6', 'V00HOURWK', 'V00INCOME', 'V00INCOME2', 'V00LIVE1', 'V00LIVE2', 'V00LIVE3', 'V00LIVE4', 'V00LIVE5', 'V00LIVENO', 'V00MARITST', 'V00MEDINS', 'V00MISSWK', 'V00PA130', 'V00PA130CV', 'V00PA130NM', 'V00PA230', 'V00PA230CV', 'V00PA330', 'V00PA330CV', 'V00PA430', 'V00PA430CV', 'V00PA530', 'V00PA530CV', 'V00PASE', 'V00PASE1', 'V00PASE1HR', 'V00PASE2', 'V00PASE2HR', 'V00PASE3', 'V00PASE3HR', 'V00PASE4', 'V00PASE4HR', 'V00PASE5', 'V00PASE5HR', 'V00PASE6', 'V00PASE6HR', 'V00WEEKWK', 'V00WKHR7CV', 'V00WORK7', 'V00WORKAMT']

P01: 233 variables
['P01KPNREV', 'P01KPNREVY', 'P01KPNR12', 'P01KPNR12M', 'P01KPNLEV', 'P01KPNLEVY', 'P01KPNL12', 'P01KPNL12M', 'P01KPACT30', 'P01HPNR12', 'P01HPNRIL', 'P01HPNROL', 'P01HPNRFL', 'P01HPNRB', 'P01HPNRLB', 'P01HPNRDK', 'P01HPNL12', 'P01HPNLIL', 'P01HPNLOL', 'P01HPNLFL', 'P01HPNLB', 'P01HPNLLB', 'P01HPNLDK', 'P01BP30', 'P01BP30OFT', 'P01BPBAD', 'P01BPUB', 'P01BPMB', 'P01BPLB', 'P01BPB', 'P01BPDK', 'P01OJPNRS', 'P01OJPNLS', 'P01OJPNRE', 'P01OJPNLE', 'P01OJPNRW', 'P01OJPNLW', 'P01OJPNRH', 'P01OJPNLH', 'P01OJPNRA', 'P01OJPNLA', 'P01OJPNRF', 'P01OJPNLF', 'P01OJPNNK', 'P01OJPNNO', 'P01TMJE6M', 'P01TMJEPN1', 'P01TMJE30D', 'P01TMJE30A', 'P01TMJF6M', 'P01TMJFPN1', 'P01TMJF30D', 'P01TMJF30A', 'P01KPR30CV', 'P01KPL30CV', 'P01KPACTCV', 'P01HPR12CV', 'P01HPL12CV', 'P01BPTOT', 'P01SXKOA', 'P01KPR12CV', 'P01KPL12CV', 'P01KPA30CV', 'P01PMRKRCV', 'P01PMLKRCV', 'P01TJE30CV', 'P01TJF30CV', 'P01TJE30WC', 'P01TJF30WC', 'P01RKSX', 'P01LKSX', 'P01LSXKOA', 'P01RSXKOA', 'P01BPDAYCV', 'P01BPBEDCV', 'P01BPACTCV', 'P01KSX', 'P01BL12SXL', 'P01BL12SXR', 'P01KPACDCV', 'P01LKP30CV', 'P01RKP30CV', 'P01RAIA', 'P01RAJS1HR', 'P01RAFT6R', 'P01RAFT6L', 'P01RAKN6R', 'P01RAKN6L', 'P01RA3YES', 'P01RA1YES', 'P01RARLYES', 'P01RATEST', 'P01RATOT3', 'P01ARTHOTH', 'P01ARTDOC', 'P01KPMED', 'P01INJR', 'P01INJR1', 'P01INJR2', 'P01INJR3', 'P01KSURGR', 'P01KRSR', 'P01KRSRA', 'P01ARTR', 'P01ARTR1', 'P01ARTR2', 'P01ARTR3', 'P01ARTRINJ', 'P01MENR', 'P01MENR1', 'P01MENR2', 'P01MENR3', 'P01MENRINJ', 'P01LRR', 'P01LRR1', 'P01LRR2', 'P01LRR3', 'P01OTSURGR', 'P01OTSR1', 'P01OTSR2', 'P01OTSR3', 'P01OTSRINJ', 'P01INJL', 'P01INJL1', 'P01INJL2', 'P01INJL3', 'P01KSURGL', 'P01KRSL', 'P01KRSLA', 'P01ARTL', 'P01ARTL1', 'P01ARTL2', 'P01ARTL3', 'P01ARTLINJ', 'P01MENL', 'P01MENL1', 'P01MENL2', 'P01MENL3', 'P01MENLINJ', 'P01LRL', 'P01LRL1', 'P01LRL2', 'P01LRL3', 'P01OTSURGL', 'P01OTSL1', 'P01OTSL2', 'P01OTSL3', 'P01OTSLINJ', 'P01HRS', 'P01HRSR', 'P01HRSROA', 'P01HRSRDK', 'P01HRSL', 'P01HRSLOA', 'P01HRSLDK', 'P01PREGEV', 'P01OVREM', 'P01OV1AGE', 'P01OV2AGE', 'P01HYS', 'P01HYSAGE', 'P01MENSTR', 'P01RAJSCV', 'P01RATSTCV', 'P01OADEGCV', 'P01OAHIPCV', 'P01OAHNDCV', 'P01OABCKCV', 'P01OAOTHCV', 'P01GOUTCV', 'P01OTARTCV', 'P01ARTDRCV', 'P01KPMEDCV', 'P01OVNUMCV', 'P01RASTASV', 'P01RATOTCV', 'P01RAWE6L', 'P01HRSRFXO', 'P01HRSLFXO', 'P01RAWE6R', 'P01STFID2', 'P01STFID1', 'P01HESTFID', 'P01HEIGHT', 'P01WEIGHT', 'P01BMI', 'P01RH1CV', 'P01RH2CV', 'P01RH3CV', 'P01RH4CV', 'P01RH5CV', 'P01LH1CV', 'P01LH2CV', 'P01LH3CV', 'P01LH4CV', 'P01LH5CV', 'P01RHBE', 'P01LHBE', 'P01BROHRCV', 'P01BROKRCV', 'P01CLAU', 'P01DADHRCV', 'P01DADKRCV', 'P01FAMHR', 'P01FAMKR', 'P01LXRKOA', 'P01LXRKOA2', 'P01MOMHRCV', 'P01MOMKRCV', 'P01MRCMP', 'P01MRIB4', 'P01MRKCBCV', 'P01MRPRBCV', 'P01OAGRDL', 'P01OAGRDR', 'P01RXRKOA', 'P01RXRKOA2', 'P01SISHRCV', 'P01SISKRCV', 'P01SVDATE', 'P01SVLKJSL', 'P01SVLKJSM', 'P01SVLKMI', 'P01SVLKOST', 'P01SVRKJSL', 'P01SVRKJSM', 'P01SVRKMI', 'P01SVRKOST', 'P01SVXRELK', 'P01SVXRLKR', 'P01SVXRRID', 'P01SVXRRKR', 'P01XRKOA']

P02: 47 variables
['P02KPN', 'P02KPNRCV', 'P02KPNLCV', 'P02KPMED', 'P02KINJ', 'P02KSURG', 'P02CNCR3', 'P02CNC3', 'P02CNC4', 'P02CNC13', 'P02CNC14', 'P02CNC15', 'P02CNMEL', 'P02CSY', 'P02CMN', 'P02CMDK', 'P02KPMEDCV', 'P02KRSCV', 'P02KSURGCV', 'P02CNCOTH', 'P02ACTRISK', 'P02DATE', 'P02ELGRISK', 'P02FAMHXKR', 'P02HR1', 'P02HR10', 'P02HR11', 'P02HR2', 'P02HR3', 'P02HR4', 'P02HR5', 'P02HR6', 'P02HR7', 'P02HR8', 'P02HR9', 'P02IKPRISK', 'P02JBMP', 'P02JBMPCV', 'P02KRS3', 'P02KRS3CV', 'P02PA1', 'P02PA2', 'P02PA3', 'P02PA4', 'P02STMED', 'P02STMEDCV', 'P02WTGA']

In [13]:
nutrition = pd.read_csv(data_dir / "oai_nutrition01_definitions.csv")
medical_history = pd.read_csv(data_dir / "oai_oarisk01_definitions.csv")
biomarkers = pd.read_csv(data_dir / "oai_labcollection01_definitions.csv")
comorbidity = pd.read_csv(data_dir / "oai_charlson01_definitions.csv")
physical = pd.read_csv(data_dir / "oai_physfunct01_definitions.csv")
depression = pd.read_csv(data_dir / "oai_ces_d01_definitions.csv")
koos = pd.read_csv(data_dir / "oai_koos_womac01_definitions.csv")
pain = pd.read_csv(data_dir / "oai_oapain01_definitions.csv")
pase = pd.read_csv(data_dir / "oai_pase01_definitions.csv")
sf_12 = pd.read_csv(data_dir / "oai_sf1201_definitions.csv")

In [14]:
columns = df.columns.tolist()

def remove_prefix(column):
    return re.sub(r'^[A-Z]\d{2}', '', column)

variables = pd.DataFrame({
    "AllClinical00": columns,
    "ElementName_candidate": [remove_prefix(c).lower() for c in columns]
})

print(variables.head())

  AllClinical00 ElementName_candidate
0            ID                    id
1       VERSION               version
2    V00BLDCOLL               bldcoll
3    V00BLDHRS1               bldhrs1
4    V00BLDHRS2               bldhrs2

In [10]:
def add_dataset_match(df, dictionary, dataset_name):
    mask = df['ElementName_candidate'].isin(dictionary['ElementName'])

    df.loc[mask, 'Dataset'] = dataset_name

    lookup = dictionary.set_index('ElementName')

    mask = df['ElementName_candidate'].isin(lookup.index)

    df.loc[mask, 'Dataset'] = dataset_name

    dictionary_fields = [
        col for col in dictionary.columns
        if col != 'ElementName'
    ]

    for field in dictionary_fields:
        if field not in df.columns:
            df[field] = None

        df.loc[mask, field] = (
            df.loc[mask, 'ElementName_candidate']
            .map(lookup[field])
        )

        
    return df

Koos/Womac data dictionary did not match AllClinical; manual mapping to then replace names

In [15]:
koos_crosswalk = pd.read_csv(data_dir / "koos_womac_crosswalk.csv")

misc_crosswalk = pd.read_csv(data_dir / "misc_crosswalk.csv")

# Remove white spaces
misc_crosswalk["AllClinical00"] = (
    misc_crosswalk["AllClinical00"].astype("string").str.strip()
)

all_crosswalk = pd.concat(
    [koos_crosswalk, misc_crosswalk],
    ignore_index=True
)


crosswalk_lookup = dict(
    zip(
        all_crosswalk["AllClinical00"],
        all_crosswalk["ElementName"]
    )
)

variables["ElementName_candidate"] = (
    variables["AllClinical00"]
    .map(crosswalk_lookup)
    .fillna(variables["ElementName_candidate"])
)

In [16]:
variables = add_dataset_match(variables, nutrition, 'Nutrition')
variables = add_dataset_match(variables, medical_history, 'Medical History')
variables = add_dataset_match(variables, biomarkers, 'Biomarkers')
variables = add_dataset_match(variables, comorbidity, 'Comorbidity')
variables = add_dataset_match(variables, physical, 'Physical Function')
variables = add_dataset_match(variables, depression, 'Depression')
variables = add_dataset_match(variables, koos, 'KOOS/WOMAC')
variables = add_dataset_match(variables, pain, 'Pain and Medication')
variables = add_dataset_match(variables, pase, 'Physical Activity')
variables = add_dataset_match(variables, sf_12, 'Medical Outcomes')

In [17]:
variables['Dataset'].value_counts(dropna=False)

Dataset
Medical History        309
Nutrition              285
Pain and Medication    197
Physical Function      170
KOOS/WOMAC              89
Biomarkers              49
Comorbidity             28
Depression              21
Physical Activity       19
Medical Outcomes        18
NaN                      2
Name: count, dtype: int64

In [18]:
variables.head()

,AllClinical00,ElementName_candidate,Dataset,DataType,Size,Required,ElementDescription,ValueRange,Notes,Aliases
0,ID,id,NaN,None,None,None,None,None,None,None
1,VERSION,version,Medical Outcomes,String,20.0,Recommended,Version/code of assessment,NaN,"e.g., Self-Report, Parent Form, Short Form, Re...",NaN
2,V00BLDCOLL,bldcoll,Biomarkers,Integer,NaN,Recommended,Phlebotomy: which draw(s) blood obtained at,0::3,0= No sample collected at visit; 1= Sample at ...,NaN
3,V00BLDHRS1,bldhrs1,Biomarkers,String,20.0,Recommended,Phlebotomy: time venipuncture completed (first...,NaN,NaN,NaN
4,V00BLDHRS2,bldhrs2,Biomarkers,String,20.0,Recommended,Phlebotomy: time venipuncture completed (repea...,NaN,NaN,NaN

In [19]:
manual_info = {
    "ID": {
        "ElementName_candidate": "id",
        "Dataset": "Participant Identifier",
        "ElementDescription": "Release ID",
    },

    "V00HANDED": {
        "ElementName_candidate": "handed",
        "Dataset": "Participant Characteristics",
        "DataType": "Integer",
        "ElementDescription": "Dominant hand for x-ray",
        "ValueRange": "0::3",
        "Notes": "1= Right handed; 2= Left handed; 3= Ambidexterous"
    },
}

for variable, info in manual_info.items():
    mask = variables["AllClinical00"] == variable
    
    for column, value in info.items():
        if column not in variables.columns:
            variables[column] = pd.NA
        
        variables.loc[mask, column] = value

In [20]:
variables.to_csv(Path("../data/processed") / "AllClinical00_variable_inventory.csv", index=False)

In [21]:
variables.head()

,AllClinical00,ElementName_candidate,Dataset,DataType,Size,Required,ElementDescription,ValueRange,Notes,Aliases
0,ID,id,Participant Identifier,None,None,None,Release ID,None,None,None
1,VERSION,version,Medical Outcomes,String,20.0,Recommended,Version/code of assessment,NaN,"e.g., Self-Report, Parent Form, Short Form, Re...",NaN
2,V00BLDCOLL,bldcoll,Biomarkers,Integer,NaN,Recommended,Phlebotomy: which draw(s) blood obtained at,0::3,0= No sample collected at visit; 1= Sample at ...,NaN
3,V00BLDHRS1,bldhrs1,Biomarkers,String,20.0,Recommended,Phlebotomy: time venipuncture completed (first...,NaN,NaN,NaN
4,V00BLDHRS2,bldhrs2,Biomarkers,String,20.0,Recommended,Phlebotomy: time venipuncture completed (repea...,NaN,NaN,NaN

In [32]:
df.head(2)

,ID,VERSION,V00BLDCOLL,V00BLDHRS1,V00BLDHRS2,V00BLDRAW1,V00BLDRAW2,V00BLSURD1,V00BLSURD2,V00CITRATE,...,V00PASE4,V00PASE4HR,V00PASE5,V00PASE5HR,V00PASE6,V00PASE6HR,V00WEEKWK,V00WKHR7CV,V00WORK7,V00WORKAMT
0,9000099,0.2.3,1: Sample at 1st collection only,35400.0,NaN,1: Yes,.: Missing Form/Incomplete Workbook,NaN,NaN,1: Sample at 1st collection only,...,0: Never,.: Missing Form/Incomplete Workbook,3: Often (5-7 days),1: Less than 1 hour,2: Sometimes (3-4 days),1: Less than 1 hour,52.0,50.0,1: Yes,1: Sitting
1,9000296,0.2.3,1: Sample at 1st collection only,30780.0,NaN,1: Yes,.: Missing Form/Incomplete Workbook,NaN,NaN,1: Sample at 1st collection only,...,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,52.0,50.0,1: Yes,2: Sitting/standing/walking

# Check empty in Allclinical

In [36]:
blank   = df.isna()
coded   = df.astype(str).apply(lambda s: s.str.startswith(".:"))
missing = blank | coded

print("Columns with most missing values:\n",missing.sum().sort_values(ascending=False).head(20) )         # cols with most missing values
print("\nPercentage of missing values per column:",(missing.mean() * 100).round(1))                              # % missing per column
print("\nMissing count per participant:",missing.sum(axis=1))                                          # missing count per participant

Columns with most missing values:
 P02CNC14      4796
V00REASW8     4796
V00REASW15    4796
P02HR11       4796
P02CMDK       4796
V00DKP400W    4796
V00RFP400W    4796
V00FFQ101     4796
V00CHELCUR    4796
V00CHELNUM    4796
V00FOLKNUM    4796
V00FOLKCUR    4796
V00URSURD2    4796
P01LRR3       4796
P01LRL2       4796
P01BPDK       4796
P01LRL3       4796
P01HRSLDK     4796
P01HPNLDK     4796
P01HRSRDK     4796
dtype: int64

Percentage of missing values per column: ID             0.0
VERSION        0.0
V00BLDCOLL     0.0
V00BLDHRS1     0.4
V00BLDHRS2    99.4
              ...
V00PASE6HR    56.7
V00WEEKWK     37.9
V00WKHR7CV     0.1
V00WORK7       0.1
V00WORKAMT    30.4
Length: 1187, dtype: float64

Missing count per participant: 0       351
1       332
2       325
3       306
4       320
       ...
4791    330
4792    350
4793    359
4794    339
4795    326
Length: 4796, dtype: int64